### ISSUE TITLE
拉取镜像出错

### ISSUE THREAD

**Issue by wqlxx** [kungze/sync-kolla-images#2]
您好，我在尝试拉取helm提供的镜像的时候遇到下面的问题
`Error response from daemon: pull access denied for registry.aliyuncs.com/kolla-helm/ubuntu-source-template-override, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
`

**Comment by jeffyjf** [comment]
这是我整理镜像列表时的一个失误，kolla 官方仓库本来就没有这个镜像，还有 registry.aliyuncs.com/kolla-helm/ubuntu-source-templates 应该也是同样的错误

**Comment by jeffyjf** [comment]
Closes #3
